name: Security audit
on:
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
  - cron: '3 3 3 * *'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        use-policy-store: true
        egress-policy: audit
        api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
