# Not run as part of pre-commit checks because they don't handle sending the correct commit
# range to `committed`
name: Lint Commits
on: [pull_request]

jobs:
  committed:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        use-policy-store: true
        egress-policy: audit
        api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

    - name: Checkout Actions Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint Commits
      uses: crate-ci/committed@master
