name: Test GitHub Action
on: [pull_request]

jobs:
  shallow:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        use-policy-store: true
        egress-policy: audit
        api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

    - name: Checkout Actions Repository
      uses: actions/checkout@v3

    - name: Prepare file with mistakes.
      run: echo "Finallizes" > file.txt
    - name: Test force pass with mistakes
      continue-on-error: true
      uses: ./
      with:
        files: ./file.txt

    - name: Prepare file with no mistakes.
      run: echo "Finalizes" > file.txt
    - name: Test pass with no mistakes
      uses: ./
      with:
        files: ./file.txt

  deep:
    name: Spell Check with Type w/History
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        use-policy-store: true
        egress-policy: audit
        api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

    - name: Checkout Actions Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Prepare file with mistakes.
      run: echo "Finallizes" > file.txt
    - name: Test force pass with mistakes
      continue-on-error: true
      uses: ./
      with:
        files: ./file.txt

    - name: Prepare file with no mistakes.
      run: echo "Finalizes" > file.txt
    - name: Test pass with no mistakes
      uses: ./
      with:
        files: ./file.txt
